language: python

sudo: false
sudo: required

env:
   matrix:
      - LUA="lua=5.1"
      - LUA="lua=5.2"
      - LUA="lua=5.3"
      - LUA="luajit=2.0"
      - LUA="luajit=2.1"

branches:
   only:
      - master

before_install:
   - pip install hererocks
   - hererocks base -r^ --$LUA
   - export PATH=$PATH:$PWD/base/bin
   - sudo add-apt-repository ppa:duggan/bats --yes
   - sudo apt-get update -qq
   - sudo apt-get install -qq bats

script:
   - cd test
   - bats .

notifications:
   email:
      on_success: change
      on_failure: always
